alpha_safety_factor: 0.99999
created: '2023-07-15 20:57:17.247896'
feature_group: general_purpose
feature_scaling_method: standardize
learning_type: static
machine_component: axis_drive
outlier_detection_model_paramters:
  KNN:
    method: largest
    n_neighbors: 5
outlier_detector_name: KNN
outlier_score_scaling: gaussian
segementation_start: 20
segmentation_end: 710
tsfresh_features: ./examples/tsfresh_features.json
tsfresh_random_forest: ./examples/tsfresh_random_forest.json
use_tsfresh_features: false
version: 0.1.1
